version: "3.9"

services:

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

  db:
    image: postgres
    container_name: postgres-db
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=bus
      - POSTGRES_DB=db
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data

  
  app:
    build: ./app
    image: marivoli/school-bus
    container_name: app
    ports:
      - 5000:5000
    volumes:
      - type: bind
        source: ./app
        target: /app
    environment:
      - SQL_HOST=db
      - SQL_PORT=5432
      

  client: 
    build: ./client
    image: marivoli/school-bus-node
    container_name: client
    ports: 
      - 80:80
      - 443:443
    volumes:
      - './client:/app'
      - '/app/node_modules'
      - /etc/letsencrypt/:/etc/letsencrypt
    depends_on:
      - app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  # nginx:
  #   build: ./client
  #   container_name: prod_nginx
  #   ports:
  #     - 80:80
  #     - 443:443
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   # networks:
  #   #   - nginx_network
  #   depends_on:
  #     - app
  #     - client
      
# networks:
#   nginx_network:
#     driver: bridge
#   postgres_network:
#     driver: bridge