version: '3.9'
services:
    pgbackups:
        image: marivoli/periodic-pgdump-over-ssh
        restart: always
        volumes:
            - ${BACKUP_DIR}:/var/opt/pgbackups
            - ~/.ssh:/root/.ssh
        environment:
            - SSH_REMOTE_USER
            - SSH_REMOTE_HOST
            - POSTGRES_DB_CONTAINER_NAME
            - POSTGRES_PORT
            - POSTGRES_DB
            - POSTGRES_USER
            - POSTGRES_PASSWORD
            - POSTGRES_EXTRA_OPTS
            - SCHEDULE
            - BACKUP_DIR
            - BACKUP_KEEP_DAYS=7
            - BACKUP_KEEP_WEEKS=4
            - BACKUP_KEEP_MONTHS=6
